### ISSUE TITLE
Features green dots

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr-site#37]
Can they be android blue?

**Comment by andrefbsantos** [comment]
Like this?
![2015-03-31-222840_1366x744_scrot](https://cloud.githubusercontent.com/assets/7232385/6929760/52e51b8a-d7f5-11e4-8b78-43e2c75a9c28.png)

Grey looks more smooth.

**Comment by algazarra** [comment]
Yeah but maybe blue with a bit less alpha. Color is welcome

**Comment by andrefbsantos** [comment]
Made it slightly darker. Changing the alpha was making the selected bullet less noticeable.

**Comment by algazarra** [comment]
Is it #00ccff?

**Comment by andrefbsantos** [comment]
#237EA0

**Comment by algazarra** [comment]
Let's use #00ccff instead

**Comment by andrefbsantos** [comment]
Hi there,

You’ve been invited by André to join the Dropbox Campus Cup! Campus Cup lets you team up with your classmates to earn up to 25 GB of free Dropbox space for two years!

To earn space, just invite friends and use Dropbox to share, collaborate, and get work done.

Join Campus Cup![2]

Note that you must be a student currently enrolled at a higher education institution in order to participate. Learn more about Campus Cup.[3]

Happy Dropboxing!


 
 Work together, win together. 

____________________________________________________
If you prefer not to receive invites from Dropbox, please go here[4].
Dropbox, Inc., PO Box 77767, San Francisco, CA 94107

[1]: https://www.dropbox.com/l/QFzyiB2m2FmG2oQ0Lgd1Dw/campuscup?text=1
[2]: https://www.dropbox.com/l/TP9JdwzToBNUmUKEu3bXPo/campuscup?text=1
[3]: https://www.dropbox.com/l/eQo8zcFIbt19HqFieQ8T2h/help/9131?text=1
[4]: https://www.dropbox.com/l/ws0FchTwDg3sIRVm1uf5qE?text=1
