### ISSUE TITLE
#nevermissatrade typo

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr-site#43]
![2015-04-07-110444_1680x999_scrot](https://cloud.githubusercontent.com/assets/7598320/7021076/fde8de7a-dd15-11e4-9330-c926d08eda86.png)

typo - it reads "nerver miss a trade"
and also, the positioning, could it be lower, like in the corner of the video for ex.

**Comment by dllud** [comment]
We cannot lower the hashtag position. Otherwise it would overlap the newsletter box on thin screens (responsive design, smartphones).

If you want the hashtag in the lower right corner you have to put the newsletter box somewhere else. Please open another issue for that when you have a proper solution.
